name: iot_prov

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  release:
    types: [published]

jobs:

  flutter_test:
    name: Run Flutter Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: "20.x"

      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze
      # Uncomment the below line if you want to run tests
      # - run: flutter test

  build_android:
    name: Build Android APK
    runs-on: ubuntu-latest
    needs: [flutter_test]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: "20.x"

      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Clean and build APK
        run: |
          flutter clean
          flutter pub get
          flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 10

  build_ios:
    name: Build iOS IPA
    runs-on: macos-12
    needs: [flutter_test]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24'

      - name: Install dependencies
        run: |
          flutter pub get
          sudo gem install cocoapods

      - name: Update Podfile to set platform version
        run: |
          cd ios
          sed -i '' "s/# platform :ios, '9.0'/platform :ios, '13.0'/" Podfile

      - name: Set up CocoaPods
        run: |
          cd ios
          pod install

      - name: Build iOS app
        run: |
          flutter build ios --release --no-codesign
          cd build/ios/iphoneos
          mkdir -p Payload
          cp -r Runner.app Payload/
          zip -r app-release.ipa Payload

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-release-ipa
          path: build/ios/iphoneos/app-release.ipa
          retention-days: 10
