name: iot_prov

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  release:
    types: [published]

jobs:
  flutter_test:
    name: Run Flutter Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v1
        with:
          java-version: "17.x"  # Ensure Java 17 is used
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter analyze

  build_apk:
    name: Build APK file
    runs-on: ubuntu-latest
    needs: [flutter_test]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v1
        with:
          java-version: "17.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter clean
      - run: flutter pub get
      - run: flutter build apk --release --build-dir=output/  # Use custom output directory

  upload_apk:
    name: Upload APK
    runs-on: ubuntu-latest
    needs: [build_apk]
    steps:
      - name: List output directory contents (Debugging)
        run: |
          echo "Listing files in output directory:"
          ls -R output/  # List files in the custom output directory

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-release-apk
          path: output/app-release.apk  # Custom path to the APK in the output directory
          retention-days: 10
