name: Stromlesser

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  release:
    types: [published]

jobs:

  flutter_test:
    name: Run Flutter Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v1
        with:
          java-version: "17.x"  # Set JDK 17
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter analyze
      # - run: flutter test

  build_apk:
    name: Build APK file
    runs-on: ubuntu-latest
    needs: [flutter_test]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v1
        with:
          java-version: "17.x"  # Set JDK 17
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter clean
      - run: flutter pub get
      - run: flutter build apk --release  # Builds APK instead of appbundle

  upload_apk:
    name: Upload APK
    runs-on: ubuntu-latest
    needs: [build_apk]
    steps:
      - name: List build directory contents (Debugging)
        run: |
          echo "Listing files in build directory:"
          ls -R build/  # Lists all files in the build directory to check if APK exists

      - name: Check for APK presence
        run: |
          echo "Checking for APK:"
          ls build/app/outputs/flutter-apk/  # Check the specific path for APK presence

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk  # Correct APK path
          retention-days: 10
