name: iot_prov

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  release:
    types: [published]

jobs:
  flutter_test:
    name: Run Flutter Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v1
        with:
          java-version: "17"  # Set Java version to 17
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter analyze

  build_appbundle:
    name: Building APK file
    runs-on: ubuntu-latest
    needs: [flutter_test]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v1
        with:
          java-version: "17"  # Set Java version to 17
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter clean
      - run: flutter pub get
      - run: flutter build appbundle

  build-ios:
    name: Build iOS and Upload IPA
    runs-on: macos-12
    needs: [flutter_test]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24'

      - name: Install dependencies
        run: |
          flutter pub get
          sudo gem install cocoapods

      - name: Create or Update Podfile to set platform version
        run: |
          cd ios
          echo "platform :ios, '13.0'" > Podfile  # Set iOS platform version to 13.0
          echo "workspace 'Runner.xcworkspace'" >> Podfile  # Ensure workspace is specified
          flutter pub get  # Ensure dependencies are up to date

      - name: Set up CocoaPods
        run: |
          cd ios
          pod install

      - name: Build iOS app
        run: |
          flutter build ios --release --no-codesign
          cd build/ios/iphoneos
          mkdir -p Payload
          cp -r Runner.app Payload/
          zip -r app-release.ipa Payload

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-release-ipa
          path: build/ios/iphoneos/app-release.ipa
          retention-days: 10
