name: iot_prov

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  release:
    types: [published]

jobs:
  flutter_test:
    name: Run Flutter Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v1
        with:
          java-version: "17.x"  # Ensure Java 17 is used
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter analyze

  build_apk:
    name: Build APK file
    runs-on: ubuntu-latest
    needs: [flutter_test]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v1
        with:
          java-version: "17.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter clean
      - run: flutter pub get
      - run: flutter build apk --release  # Builds APK instead of appbundle

  upload_apk:
    name: Upload APK
    runs-on: ubuntu-latest
    needs: [build_apk]
    steps:
      - name: List build directory contents (Debugging)
        run: |
          echo "Listing files in build directory:"
          ls -R build/  # Lists all files in the build directory to check if APK exists

      - name: Check for APK presence
        run: |
          echo "Checking for APK:"
          ls build/app/outputs/flutter-apk/  # Check the specific path for APK presence

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk  # Correct APK path
          retention-days: 10

  build-ios:
    name: Build iOS and Upload IPA
    runs-on: macos-12
    needs: [flutter_test]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24'

      - name: Install dependencies
        run: |
          flutter pub get
          sudo gem install cocoapods

      - name: Update Podfile to set platform version
        run: |
          cd ios
          sed -i '' "s/# platform :ios, '9.0'/platform :ios, '13.0'/" Podfile  # Update platform version to 13.0

      - name: Set up CocoaPods
        run: |
          cd ios
          pod install

      - name: Build iOS app
        run: |
          flutter build ios --release --no-codesign
          cd build/ios/iphoneos
          mkdir -p Payload
          cp -r Runner.app Payload/
          zip -r app-release.ipa Payload

      - name: Upload IPA Artifact (Optional - Not for now)
        uses: actions/upload-artifact@v3
        with:
          name: app-release-ipa
          path: build/ios/iphoneos/app-release.ipa
          retention-days: 10

  upload_apk_and_ipa:
    name: Upload APK and IPA
    runs-on: ubuntu-latest
    needs: [build_apk, build-ios]
    steps:
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk  # Correct APK path
          retention-days: 10
